import Head from 'next/head'
import { AppLayout } from '../components/AppLayout'
import { DirectAcces } from '../components/DirectAccess'
import { Apps } from '../constants'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout>
        {Apps.map((app, index) => (
          <DirectAcces key={index} img={app.img} title={app.title} />
        ))}
      </AppLayout>
      <style jsx>
        {`
          div {
            background-color: #fff;
            width: 60px;
            height: 60px;
            border-radius: 999px;
          }
          h3 {
            margin: 0;
          }
        `}
      </style>
    </>
  )
}
