import Head from 'next/head'
import { AppLayout } from '../components/AppLayout'
import { DirectAccess } from '../components/DirectAccess'
import { APPS, WINDOW_OPEN } from '../constants'
import { Window } from '../components/Window'
import { useRef, useState, createElement } from 'react'

export default function Home() {
  const [windowOpen, setWindowOpen] = useState(WINDOW_OPEN.NONE)
  const constraintsRef = useRef(null)

  const handleOpen = (appOpen) => {
    setWindowOpen(appOpen)
  }
  const handleClose = () => {
    setWindowOpen(WINDOW_OPEN.NONE)
  }
  return (
    <>
      <Head>
        <title>Brunao77</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout constraintsRef={constraintsRef}>
        {APPS.map((app, index) => (
          <DirectAccess
            key={index}
            onOpen={app.onOpen}
            handleOpen={handleOpen}
            img={app.img}
            title={app.title}
          />
        ))}
        {APPS.map((app) => {
          if (app.onOpen === windowOpen) {
            return (
              <Window
                dragConstraints={constraintsRef}
                tab={app.tab}
                height={app.height}
                width={app.width}
                handleClose={handleClose}
              >
                {createElement(app.component)}
              </Window>
            )
          }
          return null
        })}
      </AppLayout>
      <style jsx>{``}</style>
    </>
  )
}
