import Head from 'next/head'
import { AppLayout } from '../components/AppLayout'
import { DirectAcces } from '../components/DirectAccess'
import { APPS, WINDOW_OPEN } from '../constants'
import { Window } from '../components/Window'
import { Chrome } from '../components/Apps/Chrome'
import { Aboutme } from '../components/Apps/Aboutme'
import { Contact } from '../components/Apps/Contact'
import { useRef, useState } from 'react'

export default function Home() {
  const [windowOpen, setWindowOpen] = useState(WINDOW_OPEN.NONE)
  const constraintsRef = useRef(null)

  const handleOpen = (appOpen) => {
    setWindowOpen(appOpen)
  }
  const handleClose = () => {
    setWindowOpen(WINDOW_OPEN.NONE)
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout constraintsRef={constraintsRef}>
        {APPS.map((app, index) => (
          <DirectAcces
            key={index}
            onOpen={app.onOpen}
            handleOpen={handleOpen}
            img={app.img}
            title={app.title}
          />
        ))}
        {windowOpen === WINDOW_OPEN.CHROME && (
          <Window
            dragConstraints={constraintsRef}
            tab="Projects"
            height="650px"
            width="1000px"
            handleClose={handleClose}
          >
            <Chrome />
          </Window>
        )}
        {windowOpen === WINDOW_OPEN.CONTACT && (
          <Window
            dragConstraints={constraintsRef}
            tab="Contact"
            height="400px"
            width="700px"
            handleClose={handleClose}
          >
            <Contact />
          </Window>
        )}
        {windowOpen === WINDOW_OPEN.ABOUTME && (
          <Window
            dragConstraints={constraintsRef}
            tab="About Me"
            height="300px"
            width="700px"
            handleClose={handleClose}
          >
            <Aboutme />
          </Window>
        )}
      </AppLayout>
      <style jsx>
        {`
          div {
            background-color: #fff;
            width: 60px;
            height: 60px;
            border-radius: 999px;
          }
          h3 {
            margin: 0;
          }
        `}
      </style>
    </>
  )
}
